'use client';

import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import confetti from 'canvas-confetti';
import { Star, Lock, Check, Sparkles, MessageCircle, X, Loader2 } from 'lucide-react';

// =============================================================================
// TYPES
// =============================================================================

export interface PathStep {
  id: string;
  dayNumber: number;
  title: string;
  description: string;
  synthesis: string; // Mantra
  actionType: 'MANTRA' | 'RITUAL' | 'JOURNALING' | 'MEDITATION' | 'REFLECTION';
  isCompleted: boolean;
  unlockedAt?: string | null;
  completedAt?: string | null;
}

const TOTAL_DAYS = 30;

interface TimelineConstellationProps {
  steps: PathStep[];
  currentDay: number;
  archetype?: string;
  onCompleteStep: (stepId: string) => Promise<void>;
  onOpenChat?: () => void;
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export function TimelineConstellation({
  steps,
  currentDay,
  archetype,
  onCompleteStep,
  onOpenChat,
}: TimelineConstellationProps) {
  const [selectedStep, setSelectedStep] = useState<PathStep | null>(null);
  const [isCompleting, setIsCompleting] = useState(false);

  // Build a map of existing steps by dayNumber
  const stepsByDay = new Map<number, PathStep>();
  steps.forEach((s) => stepsByDay.set(s.dayNumber, s));

  // Build 30-day timeline slots
  const daySlots: Array<{
    day: number;
    step: PathStep | null;
    state: 'completed' | 'active' | 'locked' | 'pending';
  }> = [];
  for (let d = 1; d <= TOTAL_DAYS; d++) {
    const step = stepsByDay.get(d) || null;
    let state: 'completed' | 'active' | 'locked' | 'pending';
    if (!step) {
      state = 'pending'; // Not yet generated by backend
    } else if (step.isCompleted) {
      state = 'completed';
    } else if (step.unlockedAt) {
      state = 'active';
    } else {
      state = 'locked';
    }
    daySlots.push({ day: d, step, state });
  }

  const handleCompleteStep = useCallback(async () => {
    if (!selectedStep) return;

    setIsCompleting(true);
    try {
      await onCompleteStep(selectedStep.id);

      // Confetti explosion! 🎉
      confetti({
        particleCount: 150,
        spread: 80,
        origin: { y: 0.6 },
        colors: ['#F0E8D0', '#E8D8B8', '#D4B278', '#FFFCF5'],
      });

      // Close modal after celebration
      setTimeout(() => {
        setSelectedStep(null);
      }, 1500);
    } catch (error) {
      console.error('Failed to complete step:', error);
    } finally {
      setIsCompleting(false);
    }
  }, [selectedStep, onCompleteStep]);

  return (
    <div className="relative min-h-[600px]">
      {/* Header */}
      <div className="text-center mb-8">
        <motion.h2
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-2xl font-bold text-ivoire-100 mb-2"
        >
          Votre Chemin de Vie
        </motion.h2>
        {archetype && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="text-ivoire-400/80 text-sm"
          >
            Guidé par l&apos;archétype <span className="font-semibold">{archetype}</span>
          </motion.p>
        )}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="text-brume-200 text-xs mt-1"
        >
          Jour {currentDay} / {TOTAL_DAYS}
        </motion.p>
      </div>

      {/* Constellation Timeline */}
      <div className="relative max-w-md mx-auto">
        {/* Vertical Line */}
        <div className="absolute left-1/2 top-0 bottom-0 w-0.5 bg-gradient-to-b from-ivoire-400/30 via-brume-400/18 to-brume-700/12 transform -translate-x-1/2" />

        {/* Steps */}
        <div className="space-y-8">
          {daySlots.map((slot, index) => {
            const { day, step, state } = slot;
            const isActive = state === 'active';
            const isCompleted = state === 'completed';
            const isLocked = state === 'locked';
            const isPending = state === 'pending';
            const isInteractive = !isLocked && !isPending && step;

            return (
              <motion.div
                key={day}
                initial={{ opacity: 0, x: index % 2 === 0 ? -50 : 50 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: Math.min(index * 0.05, 1.5) }}
                className={`relative flex items-center ${
                  index % 2 === 0 ? 'flex-row' : 'flex-row-reverse'
                }`}
              >
                {/* Star Node */}
                <div className="absolute left-1/2 transform -translate-x-1/2 z-10">
                  <StarNode
                    state={
                      isPending
                        ? 'pending'
                        : state === 'active'
                          ? 'active'
                          : state === 'completed'
                            ? 'completed'
                            : 'locked'
                    }
                    dayNumber={day}
                    onClick={() => isInteractive && setSelectedStep(step!)}
                  />
                </div>

                {/* Content Card */}
                <motion.div
                  whileHover={isInteractive ? { scale: 1.02 } : {}}
                  onClick={() => isInteractive && setSelectedStep(step!)}
                  className={`
                    w-[calc(50%-40px)] p-4 rounded-xl transition-all
                    ${index % 2 === 0 ? 'mr-auto pr-8' : 'ml-auto pl-8'}
                    ${
                      isPending
                        ? 'opacity-25 cursor-default'
                        : isLocked
                          ? 'opacity-40 grayscale cursor-not-allowed'
                          : isInteractive
                            ? isActive
                              ? 'bg-gradient-to-br from-ivoire-400/12 to-brume-500/8 border border-ivoire-400/20 hover:border-ivoire-400/30 cursor-pointer'
                              : 'bg-brume-800/40 border border-brume-600/30 hover:border-ivoire-400/20 cursor-pointer'
                            : 'bg-brume-800/40 border border-brume-600/30'
                    }
                  `}
                >
                  {isPending ? (
                    <div className="text-center py-1">
                      <span className="text-xs text-brume-300">Jour {day}</span>
                      <p className="text-xs text-brume-400 italic mt-0.5">
                        En attente de canalisation
                      </p>
                    </div>
                  ) : step ? (
                    <>
                      <div className="flex items-center gap-2 mb-2">
                        <ActionIcon type={step.actionType} />
                        <span className="text-xs text-brume-200">Jour {step.dayNumber}</span>
                        {isCompleted && (
                          <span className="ml-auto text-emerald-400">
                            <Check className="w-4 h-4" />
                          </span>
                        )}
                      </div>
                      <h4
                        className={`font-medium ${isActive ? 'text-ivoire-300' : 'text-ivoire-100'}`}
                      >
                        {step.title}
                      </h4>
                      {!isLocked && (
                        <p className="text-xs text-brume-200 mt-1 line-clamp-2">
                          {step.description}
                        </p>
                      )}
                    </>
                  ) : (
                    <div className="text-center py-1">
                      <span className="text-xs text-brume-300">Jour {day}</span>
                      <p className="text-xs text-brume-400 italic mt-0.5">Verrouillé</p>
                    </div>
                  )}
                </motion.div>
              </motion.div>
            );
          })}
        </div>
      </div>

      {/* Floating Chat Button */}
      {onOpenChat && (
        <motion.button
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.5, type: 'spring' }}
          onClick={onOpenChat}
          className="fixed right-6 bottom-[calc(var(--sanctuaire-bottom-nav-h)+1rem)] lg:bottom-6 w-14 h-14 rounded-full bg-gradient-to-br from-ivoire-400 to-horizon-400 text-abyss-900 shadow-xl shadow-ivoire-400/20 flex items-center justify-center hover:from-ivoire-300 hover:to-horizon-300 transition-colors z-[45]"
          title="Parler à l'Oracle"
          aria-label="Parler à l'Oracle"
        >
          <MessageCircle className="w-6 h-6" />
          <span className="absolute -top-1 -right-1 w-4 h-4 bg-emerald-500 rounded-full flex items-center justify-center">
            <Sparkles className="w-2.5 h-2.5 text-white" />
          </span>
        </motion.button>
      )}

      {/* Step Detail Modal */}
      <AnimatePresence>
        {selectedStep && (
          <StepModal
            step={selectedStep}
            onClose={() => setSelectedStep(null)}
            onComplete={handleCompleteStep}
            isCompleting={isCompleting}
          />
        )}
      </AnimatePresence>
    </div>
  );
}

// =============================================================================
// SUB-COMPONENTS
// =============================================================================

function StarNode({
  state,
  dayNumber,
  onClick,
}: {
  state: 'locked' | 'active' | 'completed' | 'pending';
  dayNumber: number;
  onClick: () => void;
}) {
  const isActive = state === 'active';
  const isCompleted = state === 'completed';
  const isLocked = state === 'locked';
  const isPending = state === 'pending';

  return (
    <motion.button
      onClick={onClick}
      disabled={isLocked || isPending}
      animate={isActive ? { scale: [1, 1.15, 1] } : {}}
      transition={isActive ? { repeat: Infinity, duration: 2 } : {}}
      className={`
        relative w-12 h-12 rounded-full flex items-center justify-center
        transition-all cursor-pointer disabled:cursor-not-allowed
        ${
          isCompleted
            ? 'bg-gradient-to-br from-ivoire-400 to-horizon-400 shadow-lg shadow-ivoire-400/25'
            : isActive
              ? 'bg-gradient-to-br from-ivoire-400/60 to-horizon-300/50 shadow-xl shadow-ivoire-400/30'
              : isPending
                ? 'bg-brume-800/30 border border-dashed border-brume-500/25'
                : 'bg-brume-700/50 border border-brume-500/30'
        }
      `}
    >
      {/* Pulsing glow for active */}
      {isActive && (
        <>
          <motion.div
            className="absolute inset-0 rounded-full bg-ivoire-300/20"
            animate={{ scale: [1, 1.5, 1], opacity: [0.5, 0, 0.5] }}
            transition={{ repeat: Infinity, duration: 2 }}
          />
          <motion.div
            className="absolute inset-0 rounded-full bg-ivoire-400/15"
            animate={{ scale: [1, 1.8, 1], opacity: [0.3, 0, 0.3] }}
            transition={{ repeat: Infinity, duration: 2, delay: 0.3 }}
          />
        </>
      )}

      {isCompleted ? (
        <Star className="w-6 h-6 text-abyss-900 fill-current" />
      ) : isPending ? (
        <span className="text-xs text-brume-400">{dayNumber}</span>
      ) : isLocked ? (
        <Lock className="w-5 h-5 text-brume-300" />
      ) : (
        <span className="text-sm font-bold text-ivoire-100">{dayNumber}</span>
      )}
    </motion.button>
  );
}

function ActionIcon({ type }: { type: PathStep['actionType'] }) {
  const icons: Record<string, string> = {
    MANTRA: '🕉️',
    RITUAL: '🕯️',
    JOURNALING: '📝',
    MEDITATION: '🧘',
    REFLECTION: '💭',
  };
  return <span className="text-sm">{icons[type] || '✨'}</span>;
}

function StepModal({
  step,
  onClose,
  onComplete,
  isCompleting,
}: {
  step: PathStep;
  onClose: () => void;
  onComplete: () => void;
  isCompleting: boolean;
}) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-gradient-to-br from-brume-800 to-abyss-800 rounded-2xl p-6 w-full max-w-md border border-ivoire-400/20 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start justify-between mb-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <ActionIcon type={step.actionType} />
              <span className="text-sm text-ivoire-400/80">Jour {step.dayNumber}</span>
            </div>
            <h3 className="text-xl font-bold text-ivoire-100">{step.title}</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-brume-700 transition-colors text-brume-200"
            title="Fermer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Description */}
        <div className="mb-6">
          <p className="text-ivoire-200 text-sm leading-relaxed">{step.description}</p>
        </div>

        {/* Mantra/Synthesis */}
        {step.synthesis && (
          <div className="mb-6 p-4 rounded-xl bg-gradient-to-br from-ivoire-400/8 to-brume-500/5 border border-ivoire-400/12">
            <span className="text-xs text-ivoire-400/80 uppercase tracking-wider block mb-2">
              Mantra du Jour
            </span>
            <p className="text-ivoire-300 font-medium italic">&quot;{step.synthesis}&quot;</p>
          </div>
        )}

        {/* Actions */}
        <div className="flex gap-3">
          {!step.isCompleted ? (
            <button
              onClick={onComplete}
              disabled={isCompleting}
              className="flex-1 px-6 py-3 rounded-xl bg-gradient-to-r from-ivoire-400 to-horizon-400 text-abyss-900 font-bold hover:from-ivoire-300 hover:to-horizon-300 transition-colors flex items-center justify-center gap-2 disabled:opacity-70"
            >
              {isCompleting ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <>
                  <Check className="w-5 h-5" />
                  Marquer comme Complété
                </>
              )}
            </button>
          ) : (
            <div className="flex-1 px-6 py-3 rounded-xl bg-emerald-500/20 text-emerald-400 font-medium text-center border border-emerald-500/30">
              ✓ Étape Complétée
            </div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}

export default TimelineConstellation;
