import {
    Injectable,
    Logger,
    NotFoundException,
    HttpException,
    HttpStatus,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { VertexOracle, DreamContext } from '../../services/factory/VertexOracle';
import { CreateDreamDto } from './dto/create-dream.dto';
// InsightCategory is generated by Prisma — available after `prisma generate`
import { InsightCategory } from '@prisma/client';

/** Max dreams a user may submit per calendar day (UTC). Cost-control gate. */
const MAX_DREAMS_PER_DAY = 2;

@Injectable()
export class DreamsService {
    private readonly logger = new Logger(DreamsService.name);

    constructor(
        private readonly prisma: PrismaService,
        private readonly vertexOracle: VertexOracle,
    ) {}

    // -------------------------------------------------------------------------
    // POST /dreams
    // -------------------------------------------------------------------------

    async create(userId: string, dto: CreateDreamDto) {
        // ── 1. Rate-limit: max 2 dreams per UTC day ──────────────────────────
        const startOfDay = new Date();
        startOfDay.setUTCHours(0, 0, 0, 0);

        const todayCount = await this.prisma.dream.count({
            where: {
                userId,
                createdAt: { gte: startOfDay },
            },
        });

        if (todayCount >= MAX_DREAMS_PER_DAY) {
            throw new HttpException(
                {
                    statusCode: HttpStatus.TOO_MANY_REQUESTS,
                    message: `Limite atteinte : maximum ${MAX_DREAMS_PER_DAY} rêves par jour.`,
                    remainingToday: 0,
                },
                HttpStatus.TOO_MANY_REQUESTS,
            );
        }

        // ── 2. Build ONIRIQUE context from user data ─────────────────────────
        const [user, insights, spiritualPath, akashicRecord, pastDreams] = await Promise.all([
            this.prisma.user.findUnique({
                where: { id: userId },
                select: { id: true },
            }),
            this.prisma.insight.findMany({
                where: { userId },
                select: { category: true, short: true },
            }),
            this.prisma.spiritualPath.findUnique({
                where: { userId },
                include: {
                    steps: {
                        where: { isCompleted: false },
                        orderBy: { dayNumber: 'asc' },
                        take: 1,
                    },
                },
            }),
            this.prisma.akashicRecord.findUnique({
                where: { userId },
                select: { archetype: true, history: true },
            }),
            this.prisma.dream.findMany({
                where: { userId },
                orderBy: { createdAt: 'desc' },
                take: 5,
                select: { content: true, symbols: true, createdAt: true },
            }),
        ]);

        if (!user) throw new NotFoundException('User not found.');

        const todayStep = spiritualPath?.steps[0]
            ? {
                  title: spiritualPath.steps[0].title,
                  description: spiritualPath.steps[0].description,
              }
            : undefined;

        // Build a short Akashic summary string from the history array
        const akashicHistory = (akashicRecord?.history as Array<{ topic?: string; sentiment?: string }> | null) ?? [];
        const akashicSummary = akashicHistory
            .slice(-3)
            .map(h => `${h.topic ?? ''} (${h.sentiment ?? ''})`)
            .filter(Boolean)
            .join('; ') || undefined;

        const ctx: DreamContext = {
            userId,
            content: dto.content,
            emotion: dto.emotion,
            insights: insights.map(i => ({ category: i.category, short: i.short })),
            todayStep,
            pastDreams: pastDreams.map(d => ({
                content: d.content,
                symbols: d.symbols,
                createdAt: d.createdAt.toISOString().split('T')[0],
            })),
            archetype: akashicRecord?.archetype ?? spiritualPath?.archetype ?? undefined,
            akashicSummary,
        };

        // ── 3. Call ONIRIQUE agent ────────────────────────────────────────────
        this.logger.log(`[Dreams] Calling ONIRIQUE for user ${userId.substring(0, 8)}...`);
        const interpretation = await this.vertexOracle.generateDreamInterpretation(ctx);

        // ── 4. Find linked insight and step ──────────────────────────────────
        // We try to link to the most relevant insight by keyword match on first symbol
        let linkedInsightId: string | null = null;
        if (interpretation.symbols.length > 0 && insights.length > 0) {
            const domainMap: Record<string, string> = {
                amour: 'RELATIONS', relation: 'RELATIONS', couple: 'RELATIONS',
                travail: 'TRAVAIL', argent: 'FINANCE', santé: 'SANTE', corps: 'SANTE',
                âme: 'SPIRITUEL', lumière: 'SPIRITUEL', mission: 'MISSION',
                créativité: 'CREATIVITE', art: 'CREATIVITE', émotion: 'EMOTIONS',
            };
            const firstSymbol = interpretation.symbols[0].toLowerCase();
            const mappedCategory = domainMap[firstSymbol];
            if (mappedCategory) {
                const matchedInsight = await this.prisma.insight.findFirst({
                    where: { userId, category: mappedCategory as InsightCategory },
                    select: { id: true },
                });
                linkedInsightId = matchedInsight?.id ?? null;
            }
        }

        const linkedStepId = spiritualPath?.steps[0]?.id ?? null;

        // ── 5. Persist Dream ─────────────────────────────────────────────────
        const dream = await this.prisma.dream.create({
            data: {
                userId,
                content: dto.content,
                emotion: dto.emotion ?? null,
                interpretation: JSON.stringify(interpretation),
                symbols: interpretation.symbols,
                linkedInsightId,
                linkedStepId,
            },
        });

        this.logger.log(`[Dreams] Dream ${dream.id} saved for user ${userId.substring(0, 8)}.`);
        return {
            dream,
            interpretation,
            remainingToday: MAX_DREAMS_PER_DAY - todayCount - 1,
        };
    }

    // -------------------------------------------------------------------------
    // GET /dreams
    // -------------------------------------------------------------------------

    async findAll(userId: string) {
        const since = new Date();
        since.setDate(since.getDate() - 30);

        const dreams = await this.prisma.dream.findMany({
            where: {
                userId,
                createdAt: { gte: since },
            },
            orderBy: { createdAt: 'desc' },
        });

        return { dreams, total: dreams.length };
    }

    // -------------------------------------------------------------------------
    // GET /dreams/:id
    // -------------------------------------------------------------------------

    async findOne(userId: string, dreamId: string) {
        const dream = await this.prisma.dream.findFirst({
            where: { id: dreamId, userId },
        });
        if (!dream) {
            throw new NotFoundException('Dream not found.');
        }
        return dream;
    }

    // -------------------------------------------------------------------------
    // GET /dreams/patterns/analysis
    // -------------------------------------------------------------------------

    async analyzePatterns(userId: string) {
        const dreams = await this.prisma.dream.findMany({
            where: { userId },
            orderBy: { createdAt: 'desc' },
            take: 30,
            select: { content: true, symbols: true, interpretation: true, createdAt: true },
        });

        if (dreams.length < 5) {
            return {
                ready: false,
                message: `Minimum 5 rêves requis pour détecter des patterns. Tu en as ${dreams.length}.`,
                count: dreams.length,
                needed: 5 - dreams.length,
            };
        }

        // Aggregate all symbols to find most frequent
        const symbolCount: Record<string, number> = {};
        for (const dream of dreams) {
            for (const sym of dream.symbols) {
                symbolCount[sym] = (symbolCount[sym] ?? 0) + 1;
            }
        }

        const topSymbols = Object.entries(symbolCount)
            .sort(([, a], [, b]) => b - a)
            .slice(0, 10)
            .map(([symbol, count]) => ({ symbol, count }));

        // Ask Gemini for a pattern summary
        const dreamSummaries = dreams
            .slice(0, 15)
            .map((d, i) => `Rêve ${i + 1} (${d.createdAt.toISOString().split('T')[0]}): Symboles [${d.symbols.join(', ')}] — "${d.content.substring(0, 150)}"`)
            .join('\n');

        const patternPrompt = `
Tu es Oracle Lumira, guide introspectif.
INTERDICTION ABSOLUE de voyance ou de prédictions. Tu analyses des patterns oniriques récurrents.

Voici les ${dreams.length} derniers rêves de l'utilisateur:
${dreamSummaries}

Symboles les plus fréquents: ${topSymbols.map(s => `${s.symbol} (${s.count}×)`).join(', ')}

Génère un résumé introspectif des patterns récurrents (100-200 mots).
Utilise "reflet", "exploration", "mouvement intérieur" — jamais de prédictions.
Réponds en texte libre (pas JSON).
`.trim();

        let patternAnalysis: string;
        try {
            // Use CONFIDANT (flash model) for the pattern summary — it's text, not JSON
            patternAnalysis = await this.vertexOracle.chatWithUser(
                patternPrompt,
                { userId },
            );
        } catch (error) {
            this.logger.error(`[Dreams/Patterns] Gemini call failed: ${error}`);
            patternAnalysis = 'Analyse des patterns temporairement indisponible.';
        }

        return {
            ready: true,
            count: dreams.length,
            topSymbols,
            patternAnalysis,
        };
    }
}
