import {
    Controller,
    Get,
    Patch,
    Post,
    Param,
    Body,
    Request,
    UseGuards,
    Headers,
    UnauthorizedException,
    BadRequestException,
    NotFoundException,
    HttpCode,
    HttpStatus,
} from '@nestjs/common';
import { InsightsService, INSIGHT_CATEGORIES_METADATA } from './insights.service';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { UpsertInsightsDto } from './dto/upsert-insights.dto';
import { InsightCategory } from '@prisma/client';

// API Key for n8n webhook authentication
const N8N_API_KEY = process.env.N8N_INSIGHTS_API_KEY || 'lumira-n8n-insights-secret-key';

@Controller('insights')
export class InsightsController {
    constructor(private readonly insightsService: InsightsService) { }

    /**
     * GET /api/insights
     * Returns all insights for the authenticated user with category metadata
     */
    @Get()
    @UseGuards(JwtAuthGuard)
    async getUserInsights(@Request() req: { user: { userId: string } }) {
        const categories = await this.insightsService.getAllCategoriesWithInsights(req.user.userId);
        return {
            categories,
            metadata: INSIGHT_CATEGORIES_METADATA,
        };
    }

    /**
     * GET /api/insights/:category
     * Returns a specific insight by category
     */
    @Get(':category')
    @UseGuards(JwtAuthGuard)
    async getInsightByCategory(
        @Request() req: { user: { userId: string } },
        @Param('category') category: string,
    ) {
        // Validate category enum
        const upperCategory = category.toUpperCase() as InsightCategory;
        if (!Object.values(InsightCategory).includes(upperCategory)) {
            throw new BadRequestException(`Invalid category: ${category}`);
        }

        const insight = await this.insightsService.getInsightByCategory(
            req.user.userId,
            upperCategory,
        );

        if (!insight) {
            throw new NotFoundException(`No insight found for category: ${category}`);
        }

        return insight;
    }

    /**
     * PATCH /api/insights/:category/view
     * Marks an insight as viewed (removes "Nouveau" badge)
     */
    @Patch(':category/view')
    @UseGuards(JwtAuthGuard)
    async markAsViewed(
        @Request() req: { user: { userId: string } },
        @Param('category') category: string,
    ) {
        const upperCategory = category.toUpperCase() as InsightCategory;
        if (!Object.values(InsightCategory).includes(upperCategory)) {
            throw new BadRequestException(`Invalid category: ${category}`);
        }

        const insight = await this.insightsService.markAsViewed(req.user.userId, upperCategory);

        if (!insight) {
            throw new NotFoundException(`No insight found for category: ${category}`);
        }

        return { success: true, viewedAt: insight.viewedAt };
    }
}

/**
 * Separate controller for n8n webhook (different auth mechanism)
 */
@Controller('webhooks/n8n')
export class InsightsWebhookController {
    constructor(private readonly insightsService: InsightsService) { }

    /**
     * POST /api/webhooks/n8n/insights
     * Receives insights generated by n8n AI agent
     * Authenticated via X-API-Key header
     */
    @Post('insights')
    @HttpCode(HttpStatus.CREATED)
    async receiveInsights(
        @Headers('x-api-key') apiKey: string,
        @Body() dto: UpsertInsightsDto,
    ) {
        // Validate API key
        if (!apiKey || apiKey !== N8N_API_KEY) {
            throw new UnauthorizedException('Invalid or missing API key');
        }

        // Validate payload
        if (!dto.insights || dto.insights.length === 0) {
            throw new BadRequestException('No insights provided');
        }

        try {
            const result = await this.insightsService.upsertInsights(dto);
            return {
                success: true,
                message: `${result.count} insights saved successfully`,
                userId: dto.userId,
                orderId: dto.orderId,
            };
        } catch (error) {
            throw new BadRequestException(error instanceof Error ? error.message : 'Failed to save insights');
        }
    }
}
